### ISSUE TITLE
12H Time format is broken

### ISSUE THREAD

**Issue by AkaraiRP** [lisekilis/Replugged-Timestamps#3]
## Using 12H Time format (i.e. 09:00 PM, 9:00 PM, etc.) shows <t:NaN:t> instead of the timestamp version of 21:00.

First message: 21:00
Second message: 09:00 PM
![image](https://github.com/lisekilis/Replugged-Timestamps/assets/73448372/c02c1d43-4e5f-4c7f-8f9c-e56b9ba5e058)

Using Replugged-Timestamps Release v2.0.0

**Comment by lisekilis** [comment]
Fixed in the re-release of v.2.0.0
